[workspace]
resolver = "2"
members = ["crates/snapcode-core", "crates/snapcode-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.89"
license = "MIT"
repository = "https://github.com/otaviocc/snapcode"
authors = ["Otávio Cordeiro"]

[workspace.dependencies]
snapcode-core = { path = "crates/snapcode-core", version = "0.1.0" }

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.snapcode-core]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true
